### ISSUE TITLE
RFC: Add tsconfig-front.json

### ISSUE THREAD

**Issue by bastienrobert** [unlikelystudio/bases#1]
As @baloran add his `tsconfig.json` for [back-end apps](https://github.com/unlikelystudio/bases/blob/master/packages/typescript/tsconfig-backend.json), we should add our front-end configuration.

Here is my proposal:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "module": "esnext",
    "resolveJsonModule": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "noImplicitAny": true,
    "noEmit": true,
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "exclude": ["node_modules", "dist", "build", "out"]
}
```

## Motivation

I've created this config to be simple (but still solid).

## Configuration

- [allowJs](https://www.typescriptlang.org/tsconfig#allowJs) should never be enabled, you should not have any `.js(x?)` files in your app
- [forceConsistentCasingInFileNames](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames): avoid file system issues if there's case-sensitive import issues (eg. git case-sensitive issues)
- [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny) is the only `strict` property enabled function shouldn't have non-typed attributes
- [noEmit](https://www.typescriptlang.org/tsconfig#noEmit) because we use a bundler so tsc compile is useless
- [baseUrl](https://www.typescriptlang.org/tsconfig#baseUrl) is the base directory, actually it's where the `tsconfig.json` file is (for most of the time)
- [exclude](https://www.typescriptlang.org/tsconfig#exclude) modules and most commons bundled directories
- [paths](https://www.typescriptlang.org/tsconfig#paths) all paths in `src` are accessible using `@/` alias (eg. `import Foo from '@/components/Foo'` will import `Foo` from the BASE_DIR/src/components/Foo)

## Notes

Please, remember that it's not a config which should be usable for all projects but for most commons use-cases.

## Concerns

@unlikelystudio/front-end-team

**Comment by baloran** [comment]
We should do a pull request for this

**Comment by bastienrobert** [comment]
Before doing a PR it deserves discussion, right?

**Comment by simoncorompt** [comment]
Looks good to me!
